### ISSUE TITLE
load_roster_data() and return HTTPError: HTTP Error 404: Not Found 

### ISSUE THREAD

**Issue by Asukaz** [fantasydatapros/nflfastpy#2]
something wrong with data source

**Comment by MMuta52** [comment]
I am hitting the same issue!

**Comment by hchaozhe** [comment]
Same here..

**Comment by jbf302** [comment]
[This pull request](https://github.com/fantasydatapros/nflfastpy/pull/3) should fix this reported 404 issue for load_roster_data. 

My best guess:
 - the folks over @ nflverse might've moved some files around, breaking the previous URLs (this might be an continuing issue if it moves again)
 - python string/.format issues?

**Comment by MMuta52** [comment]
Yep, the url [here](https://github.com/fantasydatapros/nflfastpy/blob/master/nflfastpy/config.py#L2) is wrong. The one you want is:
https://github.com/nflverse/nflfastR-roster/blob/master/data/nflfastR-roster.csv.gz?raw=true

**Comment by bendominguez0111** [comment]
Repo has been updated to include updated roster data and schedule data. Also added injury data and depth chart data on same commit.

**Comment by carrollcj** [comment]
I'm running into this issue still. 
`
pip install nflfastpy
import nflfastpy
roster = nflfastpy.load_roster_data()
`

what am I missing? I've also tried to give it a year, but when I do that I get a separate error saying 'Load_roster_data()' doesn't take an argument.

**Comment by bendominguez0111** [comment]
@carrollcj try `pip install nflfastpy=0.0.14`

Should work
